# Generated by Django 5.0 on 2023-12-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classroom'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='activityattempt',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.activity', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='activityattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.activity'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.activity'),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.activity'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.activity'),
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(through='questions.QuestionnaireQuestion', to='questions.question'),
        ),
        migrations.AddField(
            model_name='downloadablecontent',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.week'),
        ),
        migrations.AddField(
            model_name='activity',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.week'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairequestion',
            unique_together={('questionnaire', 'question')},
        ),
    ]
