# Generated by Django 5.0 on 2023-12-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classroom'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.activity'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.activity'),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='downloadablecontent',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.week'),
        ),
        migrations.AddField(
            model_name='activity',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.week'),
        ),
    ]
