# Generated by Django 5.0 on 2023-12-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='question',
            name='activity',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_questionnaire', to='questions.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(related_name='questionnaires', through='questions.QuestionnaireQuestion', to='questions.question'),
        ),
    ]
