# Generated by Django 5.0 on 2024-01-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityparticipation',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityparticipation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='downloadablecontent',
            name='week',
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.activity')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classroom')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityAttempt',
        ),
        migrations.DeleteModel(
            name='ActivityParticipation',
        ),
        migrations.DeleteModel(
            name='DownloadableContent',
        ),
        migrations.DeleteModel(
            name='FileSubmission',
        ),
    ]
