# Generated by Django 5.0 on 2023-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_activity_teacher_remove_question_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadablecontent',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
