# Generated by Django 5.0 on 2024-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_activityinstance_end_time_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityinstance',
            name='classroom',
        ),
        migrations.AddField(
            model_name='activityinstance',
            name='classrooms',
            field=models.ManyToManyField(to='users.classroom'),
        ),
    ]
