# Generated by Django 5.0 on 2023-12-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_studentquestionnaireresponse_questionresponsedetail'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionresponsedetail',
            options={'verbose_name': 'Question Response Detail', 'verbose_name_plural': 'Question Response Details'},
        ),
        migrations.AlterModelOptions(
            name='studentquestionnaireresponse',
            options={'verbose_name': 'Student Questionnaire Response', 'verbose_name_plural': 'Student Questionnaire Responses'},
        ),
        migrations.AlterUniqueTogether(
            name='questionresponsedetail',
            unique_together={('student_response', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='studentquestionnaireresponse',
            unique_together={('student', 'questionnaire')},
        ),
    ]
