# Generated by Django 5.0 on 2024-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(default='Not provided', max_length=20),
        ),
    ]
